name: Create billing project test
on:
  push:
    branches:
      - arh-testing

jobs:
  main-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1.2
        with:
          version: 1.6.1
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-poetry-v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./tools/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        id: dependencies
        run: poetry install
        working-directory: ${{ github.workspace }}/tools
      - name: Run script
        run: python -m billing_project
        working-directory: ${{ github.workspace }}/tools